<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<testsuites name="utf test.lvproj">
	<testsuite assertions="0" disabled="0" errors="0" failures="1" name="utf test.lvproj\My Computer\add fail.lvtest" skipped="0" skips="0" tests="2" time="0.977000" timestamp="0.000000">
		<testcase assertions="0" name="Test Case 1" time="107.000000" timestamp="0.000000"/>
		<testcase assertions="0" name="Test Case 2" time="39.000000" timestamp="0.000000">
			<failure></failure>
		</testcase>
	</testsuite>
	<testsuite assertions="0" disabled="0" errors="0" failures="0" name="utf test.lvproj\My Computer\add.lvtest" skipped="0" skips="0" tests="2" time="0.833000" timestamp="0.000000">
		<testcase assertions="0" name="Test Case 1" time="22.000000" timestamp="0.000000"/>
		<testcase assertions="0" name="Test Case 2" time="41.000000" timestamp="0.000000"/>
	</testsuite>
	<testsuite assertions="0" disabled="0" errors="2" failures="0" name="utf test.lvproj\My Computer\broken add.lvtest" skipped="0" skips="0" tests="0" time="0.000000" timestamp="0.000000">
		<testcase assertions="0" name="1" time="0.000000" timestamp="0.000000">
			<error message="Possible reason(s):&#xA;&#xA;The VI under test is broken." type="VIError"></error>
		</testcase>
		<testcase assertions="0" name="2" time="0.000000" timestamp="0.000000">
			<error message="Possible reason(s):&#xA;&#xA;The VI under test is broken." type="VIError"></error>
		</testcase>
	</testsuite>
	<testsuite assertions="0" disabled="0" errors="0" failures="0" name="utf test.lvproj\My Computer\add skip.lvtest" skipped="1" skips="0" tests="0" time="0.000000" timestamp="0.000000">
		<testcase assertions="0" name="1" time="0.000000" timestamp="0.000000">
			<skipped></skipped>
		</testcase>
	</testsuite>
</testsuites>